abcxyz/lumberjack

clients/java-logger/library/pom.xml
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/AuditLoggingServerInterceptor.java
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/config/AuditLoggingConfiguration.java
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/modules/AuditLoggingModule.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/AuditLoggingServerInterceptorTests.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/config/AuditLoggingConfigurationTest.java
clients/java-logger/library/src/test/resources/minimal_with_labels.yml

feat: add java jvs integration

---

integration/testrunner/grpcrunner/grpc.go
integration/testrunner/httprunner/http.go

Fix: https://github.com/abcxyz/lumberjack/issues/263

chore: optimize bigquery exists query in integ tests

---

clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/AuditLoggingServerInterceptor.java
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/JustificationProcessor.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/AuditLoggingServerInterceptorTests.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/processor/JustificationProcessorTests.java
integration/testrunner/grpcrunner/grpc.go

Fixes: https://github.com/abcxyz/lumberjack/issues/265
Similar to Go client change in: https://github.com/abcxyz/lumberjack/pull/272
My formatter did a bunch of changes and I don't know if it's the proper. I think my VS code is using https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml
p.s. This is my first java code change in like 7 years.

feat: Java client - add util lib to validate and fill justification in logs

---

.github/workflows/cleanup.yml
clients/go/pkg/audit/runtime.go
clients/go/pkg/auditopt/config.go
clients/go/pkg/auditopt/config_test.go
clients/go/pkg/cloudlogging/processor.go
clients/go/pkg/filtering/processor.go
clients/go/pkg/remote/processor.go

Old docker images might be cleaned up

Do not pin gcr-cleaner

---

README.md
docs/clients.md
docs/config.md
docs/grpc.md
docs/setup.md
docs/testing.md

- Added Go examples but need a little help on Java examples (will follow up).
- Pending less user facing docs (testing and setup)

doc: break down and refine docs

---

clients/go/apis/v1alpha1/config.go
clients/go/apis/v1alpha1/config_test.go
clients/go/pkg/auditopt/config.go
clients/go/pkg/auditopt/config_test.go

refactor justificiation config(golang)

---

clients/go/pkg/auditopt/config.go

Fix: https://github.com/abcxyz/lumberjack/issues/289

doc: add godoc example for auditopt

---

clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/AuditLoggingServerInterceptor.java
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/LoggingClientBuilder.java
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/JustificationProcessor.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/AuditLoggingServerInterceptorTests.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/processor/JustificationProcessorTests.java

to address [issue 283](https://github.com/abcxyz/lumberjack/issues/283) java side refactoring

feat: refactor JustificationProcessor(Java)

---

clients/go/pkg/justification/processor.go
clients/go/pkg/justification/processor_test.go

feat: Populate standard audit log field for justification

---

clients/go/pkg/auditopt/config.go

https://github.com/abcxyz/lumberjack/issues/297

fix: set jvs config properly to initialize jvs client

---

clients/java-logger/library/pom.xml

There's a couple security issues, especially with YAML

Update java deps

---

clients/java-logger/grpc-test-app/pom.xml
clients/java-logger/shell/pom.xml

I didn't realize we had some many POMs

Update more Java deps

---

clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/JustificationProcessor.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/processor/JustificationProcessorTests.java

java client side change for issue #266

feat: populate standard audit log field for justification(java client)

---

.github/workflows/cleanup.yml
.github/workflows/test-unit.yml

Now that we have a single Go module, this gets a bit simpler :)

Reduce the number of tests

---

docs/clients.md
docs/grpc.md

#277 
1. java client does not support custom processors, discussed with Chen that we will support that when requested.
2.  used md format to format the files touched.

docs: add java client set up guide

---

clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/LoggingClientBuilder.java
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/FilteringProcessor.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/LoggingClientTests.java

fix: change filtering processor to log validator

---

.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore

These are the issues I ran into when trying out the jvs release. See:
- https://github.com/abcxyz/jvs/pull/152
- https://github.com/abcxyz/jvs/pull/153
- https://github.com/abcxyz/jvs/pull/154

fix: issues in the release workflow

---

clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/config/CloudLoggingConfiguration.java
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/modules/AuditLoggingConfigurationModule.java
docs/clients.md
docs/config.md

Fix: https://github.com/abcxyz/lumberjack/issues/333

fix: java client config env var and doc update 

---

.github/workflows/ci.yml

fixed terraform clean up, should use `terraform apply -destroy`

fix: fixed terraform clean up

---

integration/testrunner/grpcrunner/grpc.go
integration/testrunner/httprunner/http.go

feat: add more fields validation in e2e test

---

.github/workflows/ci.yml
.github/workflows/cleanup.yml
.github/workflows/release.yml

Also exclude pinning any CI/CD workflows we control

Update CI pins

---

clients/go/apis/v1alpha1/config.go
clients/go/apis/v1alpha1/config_test.go
clients/go/pkg/auditopt/config.go
clients/go/pkg/auditopt/config_test.go
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/config/AuditLoggingConfiguration.java
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/config/Justification.java
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/modules/AuditLoggingModule.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/config/AuditLoggingConfigurationTest.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/config/JustificationTest.java
clients/java-logger/library/src/test/resources/minimal_with_labels_jvs.yml
docs/clients.md
docs/config.md

part of #203 
tested the env var locally.

fix: add allowBreakglass in both go and java client

---

clients/go/apis/v1alpha1/config.go
clients/go/apis/v1alpha1/config_test.go
clients/go/pkg/auditopt/config_test.go
clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/config/AuditLoggingConfiguration.java
clients/java-logger/library/src/test/java/com/abcxyz/lumberjack/auditlogclient/config/AuditLoggingConfigurationTest.java

Fix: https://github.com/abcxyz/lumberjack/issues/378

feat: default to fail_close log mode

---

protos/v1alpha1/audit_log_request.proto

Fix: https://github.com/abcxyz/lumberjack/issues/407

feat: introduce new log types

---

README.md

Other kinds of audit logs that can leverage lumberjack

doc: about other kinds of audit logs

---

README.md
docs/cli.md

chore: add validation cli tool doc

---

.goreleaser.yaml

feat: add binary release for lumberctl

---

clients/go/test/shell/main.go
go.mod
go.sum

https://github.com/abcxyz/lumberjack/security/code-scanning/1

Sanitize trace value from user-supplied header to avoid reflective XSS

---

.github/workflows/release.yml
.gitignore
clients/java-logger/library/pom.xml

added maven flattern plugin otherwise it will not be consumable by Maven. See https://maven.apache.org/maven-ci-friendly.html#install-deploy

fix: use flatten-maven-plugin

---

integration/testrunner/db.go

bqclient is not providing significant value for this test function, and it introduces many unnecessary layers of indirection.

Drop bqclient

---

clients/go/pkg/audit/interceptor.go
clients/go/pkg/audit/interceptor_test.go
clients/go/pkg/auditerrors/auditerrors.go
clients/go/pkg/auditerrors/auditerrors_test.go

Fix: https://github.com/abcxyz/lumberjack/issues/480

Add helper func to tell if its an interceptor error

---

clients/go/apis/v1alpha1/auditlogutil_test.go
clients/go/apis/v1alpha1/config_test.go
clients/go/pkg/audit/client_test.go
clients/go/pkg/audit/interceptor.go
clients/go/pkg/audit/interceptor_test.go
clients/go/pkg/audit/labels_test.go
clients/go/pkg/audit/rules_test.go
clients/go/pkg/audit/runtime_test.go
clients/go/pkg/audit/validation_test.go
clients/go/pkg/auditopt/config_test.go
clients/go/pkg/cloudlogging/processor_test.go
clients/go/pkg/filtering/processor_test.go
clients/go/pkg/justification/processor_test.go
clients/go/pkg/remote/processor_test.go
clients/go/pkg/security/grpc_test.go
pkg/cli/tail_test.go
pkg/cli/validate_test.go
pkg/cloudlogging/puller_test.go
pkg/server/server_test.go
pkg/validation/validation_test.go

This is no longer required as of Go 1.22+

Remove shadowed loop variables
